ДЗ1 Часть 1
IfuryI/mail_GO pull request #1
Opened 2021-03-08 10:18 UTC by IfuryI

2021-03-08 21:28 UTC, bulletmys requested changes

2021-03-08 21:28 UTC, bulletmys commented on task1/main.go
> +	CFlag := flag.Bool("c", false, "")
Нужно добавить описание флагам

2021-03-08 21:28 UTC, bulletmys commented on task1/main.go
> +			*fin, err = os.Open(flag.Args()[0])
не закрываешь тут файлы

2021-03-08 21:28 UTC, bulletmys commented on task1/main.go
> +func readIOFileFlags(fin **os.File, fout **os.File) error {
Идея хорошая входной и выходной поток закрыть за интерфейсом, только почему os.File, а не io.Reader/io.Writer?

2021-03-08 21:28 UTC, bulletmys commented on task1/main.go
> +	FFlag := flag.Int("f",  0, "")
нет проверки, что флаги f и s не отрицательные

2021-03-08 21:28 UTC, bulletmys commented on task1/main.go
> +type options struct {
Лучше в человеко-понятном формате написать флаги – по их предназначению (ignoreCase и тд)

2021-03-08 21:28 UTC, bulletmys commented on task1/main.go
> +		}
Можно же объеденить

2021-03-08 21:28 UTC, bulletmys commented on task1/main.go
> +	if !opt.c && !opt.d && !opt.u {
Этот if можно объединить с последним

2021-03-08 21:28 UTC, bulletmys commented on task1/table_test.go
> +package main
Добавь тесты на негативные случаи – ошибки флагов и тд

2021-03-08 21:28 UTC, bulletmys commented on task2/main.go
> +package main
Нужна проверка на некорректные данные, например `"3^2"`, `"23+(12+(14)"`, `""`, `"23/0"` и тд

2021-03-08 21:28 UTC, bulletmys commented on task2/main.go
> +			printHelp();
флешбеки с сишки ставить точку с запятой?)

2021-03-08 21:28 UTC, bulletmys commented on task2/main.go
> +		*(*uintptr)(unsafe.Pointer(&(*p).input))++
Уфф, ну хз, насколько оправданно юзать unsafe – лучше найти иные способы. У тебя довольно необычная реализация, обычно юзают польскую нотацию для данной задачи

2021-03-08 21:28 UTC, bulletmys commented on task2/table_test.go
> +			t.Fatalf("Failed: " + strconv.Itoa(i) + " " + test.input)
Лучше еще писать какой ответ ожидали и какой получили

2021-03-10 23:17 UTC, IfuryI commented on task1/main.go
> +	CFlag := flag.Bool("c", false, "")
Добавил

2021-03-10 23:17 UTC, IfuryI commented on task1/main.go
> +			*fin, err = os.Open(flag.Args()[0])
Они в другой функции через defer закрываются

2021-03-10 23:18 UTC, IfuryI commented on task1/main.go
> +	FFlag := flag.Int("f",  0, "")
Сделал проверку

2021-03-10 23:18 UTC, IfuryI commented on task1/main.go
> +type options struct {
Сделал

2021-03-10 23:18 UTC, IfuryI commented on task1/main.go
> +		}
Объединил

2021-03-10 23:18 UTC, IfuryI commented on task1/main.go
> +	if !opt.c && !opt.d && !opt.u {
Объединил

2021-03-10 23:19 UTC, IfuryI commented on task1/table_test.go
> +package main
Добавил негативные тесты

2021-03-10 23:19 UTC, IfuryI commented on task2/main.go
> +package main
Добавил негативные тесты

2021-03-10 23:19 UTC, IfuryI commented on task2/main.go
> +			printHelp();
да ахахах

2021-03-10 23:23 UTC, IfuryI commented on task2/main.go
> +		*(*uintptr)(unsafe.Pointer(&(*p).input))++
Ну здесь вроде для этого алгоритма норм unsafe, просто в го нельзя указатель на первый элемент двигать, а как сделать по другому я не нашел. Но да, я понял, unsafe'ом лучше не пользоваться

2021-03-10 23:23 UTC, IfuryI commented on task2/main.go
> +		*(*uintptr)(unsafe.Pointer(&(*p).input))++
И лучше бы я тоже сделал через польскую нотацию...

2021-03-10 23:24 UTC, IfuryI commented on task2/table_test.go
> +			t.Fatalf("Failed: " + strconv.Itoa(i) + " " + test.input)
Сделал для позитивных тестов

2021-03-11 10:47 UTC, bulletmys approved these changes

2021-03-11 20:01 UTC, merged